#!/bin/bash

if [ "${BASH_SOURCE}" = "${0}" ]; then
	printf "\n[ERROR]: This script needs to be sourced\n\n"
else
	DEY_INSTALLDIR="/home/docker/nexis"
	cd $(dirname ${BASH_SOURCE})
	. ${DEY_INSTALLDIR}/sources/poky/oe-init-build-env .

	# Add our own scripts directory to the PATH
	PATH="$(echo $PATH | sed -e "s,:?${DEY_INSTALLDIR}/sources/meta-digi/scripts,,g;s,^:,,g")"
	export PATH="${DEY_INSTALLDIR}/sources/meta-digi/scripts:$PATH"

	unset DEY_INSTALLDIR
fi
